apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
  labels:
    app.kubernetes.io/name: fastapi-app
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    name: http
  selector:
    app.kubernetes.io/name: fastapi-app
