apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config

  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: gitops-pipeline
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: postgres
